### ISSUE TITLE
Windows Fluidpatcher setup program fails -- and provides insufficient info to troubleshoot

### ISSUE THREAD

**Issue by gmeader** [GeekFunkLabs/fluidpatcher#104]
Running setup_fluidpatcher_win64.exe on a Win 10 box fails with the attached image error message.

It should list the Python packages it is failing to install

![FluidPatcher-Failed](https://github.com/GeekFunkLabs/fluidpatcher/assets/10481183/906bb1b3-8809-4f59-a100-597772b4b5ef)

**Comment by albedozero** [comment]
Ported GUI to tkinter, which simplifies install, to the point where a Windows installer isn't really necessary. See [docs](https://geekfunklabs.github.io/fluidpatcher/#requirements) for installation details.
