### ISSUE TITLE
ImportError: cannot import name 'time_ns'

### ISSUE THREAD

**Issue by berthelemy** [GeekFunkLabs/fluidpatcher#17]
Hi there,

Running Python 3.5.3 on Raspian "Stretch"

I get this error when running headlesspi.py:

ImportError: cannot import name 'time_ns'

Traceback:

```

File "headlesspi.py", line 10, in <module>
from utils import netlink
File "/home/pi/headlesspi/utils/netlink.py", line 5, in <module>
from time import time_ns

```

I replaced line 5 with `import time`, which took me further through the application.

But then I got another error (reporting separately)

**Comment by albedozero** [comment]
It sounds like you may be running the script from the command line with Python 2 instead of Python 3, and this code is Python3-specific. The command should be

```
python3 headlesspi.py
```

Let me know if that still doesn't work!
