### ISSUE TITLE
TypeError: '_sre.SRE_Match' object is not subscriptable

### ISSUE THREAD

**Issue by berthelemy** [GeekFunkLabs/fluidpatcher#18]
Hi there,

Running Python 3.5.3 on Raspian "Stretch"

I get this error when running headlesspi.py (once I'd fixed the error noted in #17 )

TypeError: '_sre.SRE_Match' object is not subscriptable

Traceback:

```

File "headlesspi.py", line 106, in <module>
    fport = re.search("client (\d+): 'FLUID Synth", subprocess.check_output(['aconnect', '-o']).decode())[1]
TypeError: '_sre.SRE_Match' object is not subscriptable

```

The console messages before this point were:

fluidsynth: warning: Requested a period size of 64, got 444 instead
fluidsynth: Connection of Midi Through Port-0 succeeded
fluidsynth: Connection of Keystation Mini 32 MIDI 1 succeeded
fluidsynth: warning: Connection Midi Through Port-0 is already subscribed
fluidsynth: warning: Connection Keystation Mini 32 MIDI 1 is already subscribed

Any thoughts? I'm not quite sure what's happening here.

Thanks,

Mark

**Comment by albedozero** [comment]
See my comment on #17
