### ISSUE TITLE
libfluidsynth package doesnt seem to be available on Ubuntu focal 20.04

### ISSUE THREAD

**Issue by clendee** [GeekFunkLabs/fluidpatcher#22]
Hi,

I tried following the install instructions, mainly to put fluidpatcher on my Ubuntu focal 20.04 desktop so that I can try to push patches to my Pi running the synth software.
`
sudo apt install libfluidsynth`

I get the error:
`E: Unable to locate package libfluidsynth`

I notice libfluidsynth2 is available for my distribution but once I try to open the patcher python starts coughing up errors.

**Comment by albedozero** [comment]
Interesting - I haven't seen a distro with libfluidsynth2 available yet, and it's also strange to see 2 available but not 1. Your best bet is probably to just build fluidsynth from source on Ubuntu - it's quite easy with the cmake system they have set up. You can follow the instructions in the [FluidSynth wiki](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake), or you can use the [squishbox-install.bash](https://github.com/albedozero/fluidpatcher/blob/master/assets/squishbox-install.bash) script - just comment out the [line](https://github.com/albedozero/fluidpatcher/blob/20294fd461f3d5d0c55930be27c7abe8ca5300b4/assets/squishbox-install.bash#L211) that tries to install libfluidsynth1

I suspect there's something goofy with the libfluidsynth2 version in the Ubuntu focal repo if you're getting lots of error messages - if you have time to share them here I could troubleshoot

**Comment by clendee** [comment]
Hi,
Here is a screenshot of libfluidsynth2 available in focal (20.04) from the Ubuntu Packages site.  I was searching for libfluidsynth but only libfluidsynth2 appears.

I'll show you the python errors this evening perhaps.  I'll keep you posted.

![image](https://user-images.githubusercontent.com/50013459/140702638-0ab951ed-b408-424c-a1cc-62b26bdc8dde.png)

**Comment by albedozero** [comment]
In any case, I'm thinking the instructions and install script should just use `fluidsynth` as a target, and not `libfluidsynth` since the former will point at the newest available version. It's good to see the newer versions of Debian/Ubuntu have switched to fluidsynth 2, as it's definitely better. If you do post the Python errors, would you also be able to post the results of

```
sudo apt-cache policy libfluidsynth2
```
or
```
sudo apt-cache policy fluidsynth
```
This way I can see if I created some version-specific bug. There's been a lot of development going on over there.

**Comment by clendee** [comment]
Sorry for the delay in getting some of this information to you, life gets in the way sometimes.

![image](https://user-images.githubusercontent.com/50013459/142756251-cbc30dfa-d520-46bb-8e56-bd4d94126896.png)

**Comment by albedozero** [comment]
I added some methods in a [recent commit](https://github.com/albedozero/fluidpatcher/commit/e0580682913ef5c0e528949ba94b47d59f141da1) that actually query the running instance of fluidsynth for its version number, so I can work around some of the differences in recent versions :) This should prevent code barfs if the most recent version of fluidsynth isn't installed. The install script has also been updated to use better repo targets in light of the recent jump to Debian 11.
