### ISSUE TITLE
Error in bank0 Elevator Jam preset

### ISSUE THREAD

**Issue by BeFrankly** [GeekFunkLabs/fluidpatcher#51]
Hello,
actual version of bank0 seems to have an error in the Elevator jam preset. Each time I switch to it by running headlesspi.py in a SSH session the output is:

<pre>elected patch 4/5: Cheap Synth
Exception ignored on calling ctypes callback function: &lt;bound method Synth.custom_midi_router of &lt;patcher.fswrap.Synth object at 0x7f9d8b1f70&gt;&gt;
Traceback (most recent call last):
  File &quot;/home/pi/Synthy/patcher/fswrap.py&quot;, line 694, in custom_midi_router
    if self.msg_callback: self.msg_callback(res)
  File &quot;/home/pi/Synthy/./headlesspi.py&quot;, line 152, in listener
    self.select_patch((self.pno + msg.patch) % len(pxr.patches))
  File &quot;/home/pi/Synthy/./headlesspi.py&quot;, line 141, in select_patch
    pxr.apply_patch(self.pno)
  File &quot;/home/pi/Synthy/patcher/__init__.py&quot;, line 163, in apply_patch
    self._fluid.player_add(name, **{**info, &apos;file&apos;: fpath, &apos;chan&apos;: pchan})
  File &quot;/home/pi/Synthy/patcher/fswrap.py&quot;, line 820, in player_add
    self.players[name] = Player(self, file, loops, barlength, chan, mask)
  File &quot;/home/pi/Synthy/patcher/fswrap.py&quot;, line 499, in __init__
    FL.fluid_midi_router_add_rule(self.frouter, rule, rtype)
ctypes.ArgumentError: argument 3: &lt;class &apos;TypeError&apos;&gt;: wrong type
</pre>
If you comment out this part of the preset

  players:
       groove:
       file: elevatorgroove.mid
       chan: 1-10*1+5 # shift channels of messages in song
       barlength: 1536 # if given, finishes measure before seeking
       loops: [15350, 18419] # pairs of begin, end ticks

the error is not comming up.

Could you check this?
Regards
Frank

**Comment by albedozero** [comment]
Thanks! Bank0.yaml is fine, it was actually a bug in the Player code. This is fixed by db44a5d and added to [v0.7.9](https://github.com/albedozero/fluidpatcher/releases/tag/v0.7.9).
