### ISSUE TITLE
fluidpather won't install with python 11 , wxpython throws bugs while installing

### ISSUE THREAD

**Issue by bobobo-git** [GeekFunkLabs/fluidpatcher#64]
hi
i tried to install fluidpatcher with python 3.11 on win 64

wxpython ist compatible to python 3.10 so it won't run on the python 3.11
the fluidpatcher setup fails with some errormessages and can't be startet

in conclusion i can't use fluidpatcher on win 64 with python 3.11

greetings

**Comment by albedozero** [comment]
Thanks - the installer in the [0.7.13](https://github.com/albedozero/fluidpatcher/releases/tag/v0.7.13) release checks for python 3.10 (3.9 for 32-bit) and installs if needed. The shortcuts created will now launch python 3.10 (3.9) specifically.
