### ISSUE TITLE
squishbox-install.bash no longer works

### ISSUE THREAD

**Issue by RocketManRC** [GeekFunkLabs/fluidpatcher#83]
**Describe the bug**
The script squishbox-install.bash no longer works as is because the Github account has changed name from albedozero to GeekFunkLabs and the script still references albedozero.

**Workaround**
A workaround is to download the script and edit it replacing all references to albedozero with GeekFunkLabs then run it locally.

**Comment by albedozero** [comment]
Thanks - this should be fixed now in release 0.8
