### ISSUE TITLE
Problems installing fluid-soundfont-gm!

### ISSUE THREAD

**Issue by ik2wxx** [GeekFunkLabs/fluidpatcher#89]
Hello
After start install procedure with 

`curl -L git.io/squishbox | bash
`
and replying to option request, the install script fails with this error

_Problems installing fluid-soundfont-gm!_

I'm on a PI with Raspbian GNU/Linux 11 (bullseye)

Any help please....

**Comment by albedozero** [comment]
This is most frequently a problem with the system giving up on installing the package because of a temporarily slow internet connection, or a lower-quality/corrupted SD card that can't verify the writes fast enough. Try installing the package from the command line and see what output you get:
```
sudo apt-get install fluid-soundfont-gm
```
