### ISSUE TITLE
Save patch issue

### ISSUE THREAD

**Issue by tizfra** [GeekFunkLabs/fluidpatcher#97]
On Squishbox 0.8.4 (v4 hardware),
when I want to add new patch and I want to save it, i see the following error: `name 'mode' is not defined` and Squishbox doesn't save the patch.

To add the new patch I select `open soundfont`, then I select the soundfont I want to add and I click on the two button to see the check mark (is the only way I found to see the check mark to save the patch). At this time I see the error.

Can you help me?

**Comment by albedozero** [comment]
Thanks for tracking down my bugs 😅 !

The way the "Open Soundfont" menu is supposed to work is that once you choose the soundfont to open, you can scroll through its presets and play them. Pressing and holding the encoder on a preset will let you add that preset as a new patch in your bank, but first you have the opportunity to modify the name. Press and hold the stompbutton to exit character input mode, and you'll get the check/X toggle to confirm/deny adding the new patch. Either way you return to the soundfont, so you can add more presets if desired. Press and hold the stompswitch to exit the soundfont and go back to your bank, now with any of the additional patches you added.
